apiVersion: v1
kind: Service
metadata:
  name: thanos-querier
  namespace: monitoring
  labels:
    app: thanos-querier
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9090
    targetPort: http
  selector:
    app: thanos-querier