apiVersion: v1
kind: Service
metadata:
  name: thanos-querier-svc
  namespace: monitoring
  labels:
    app: thanos-querier-svc
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: /metrics
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9090
    targetPort: http
    protocol: TCP
  selector:
    app: thanos-querier